version: '3'
services:
  php-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8001:80"
    volumes:
      - ./:/var/www/html
    links:
      - db
    depends_on:
      - db

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: your_password
      MYSQL_DATABASE: real_estate
    volumes:
      - db-data:/var/lib/mysql

volumes:
  db-data:
