version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php-web
    volumes:
      - .:/var/www/html
    ports:
      - "8086:80"
    networks:
      - app-network
    depends_on:
      - mysql-container

  mysql-container:
    image: mysql:5.7
    container_name: mysql-container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: your_password
      MYSQL_DATABASE: real_estate
      MYSQL_USER: root
      MYSQL_PASSWORD: your_password
    ports:
      - "3306:3306"
    networks:
      - app-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    ports:
      - "8181:80"
    environment:
      PMA_HOST: mysql-container
      MYSQL_ROOT_PASSWORD: your_password
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
