version: '4.30'

services:
  www:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "8004:80"
    volumes:
      - ./www:/var/www/html
    depends_on:
      - mysql_container
    networks:
      - real-estate-website_network

  mysql_container:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: your_password
      MYSQL_DATABASE: real_estate
      MYSQL_USER: root
      MYSQL_PASSWORD: your_password
    ports:
      - "3310:3310"
    volumes:
      - ./database:/docker-entrypoint-initdb.d
      - mysql_container_data:/var/lib/mysql
    networks:
      - real-estate-website_network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "82:80"
    environment:
      MYSQL_ROOT_PASSWORD: your_password
      MYSQL_USER: root
      MYSQL_PASSWORD: your_password
      PMA_HOST: mysql_container  # Add this line to specify the MySQL hostname
    networks:
      - real-estate-website_network
    depends_on:
      - mysql_container

networks:
  real-estate-website_network:

volumes:
  mysql_container_data:
